/**
 * SILENCE SENTINEL — GitHub Reporter
 *
 * Generates markdown reports suitable for PR comments.
 * Includes pass/fail per guard, violations list, compliance score,
 * and visual indicators.
 */

import type { ComplianceReport, GuardResult } from "../analyzers/compliance-scorer.js";

/**
 * Generate a full markdown report for a PR comment.
 */
export function generateMarkdownReport(report: ComplianceReport): string {
  const lines: string[] = [];

  // Header
  lines.push("## SILENCE SENTINEL Report");
  lines.push("");

  // Score badge
  const scoreEmoji = getScoreEmoji(report.score);
  lines.push(
    `**Compliance Score:** ${scoreEmoji} **${report.score}/100** (Grade: **${report.grade}**)`
  );
  lines.push("");

  // Overall status
  if (report.passed) {
    lines.push("> **Status:** All checks passed. Deploy authorized.");
  } else {
    lines.push(
      "> **Status:** Violations detected. Review required before merge."
    );
  }
  lines.push("");

  // Guard results table
  lines.push("### Guard Results");
  lines.push("");
  lines.push("| Guard | Status | Violations |");
  lines.push("|-------|--------|------------|");

  for (const result of report.results) {
    const status = result.passed ? "PASS" : "FAIL";
    const statusIcon = result.passed ? "![pass]()" : "![fail]()";
    lines.push(
      `| ${formatGuardName(result.guard)} | ${statusIcon} ${status} | ${result.violations} |`
    );
  }
  lines.push("");

  // Violation details
  const failedGuards = report.results.filter((r) => !r.passed);
  if (failedGuards.length > 0) {
    lines.push("### Violations");
    lines.push("");

    for (const guard of failedGuards) {
      lines.push(`#### ${formatGuardName(guard.guard)}`);
      lines.push("");

      for (const detail of guard.details) {
        lines.push(`- ${detail}`);
      }
      lines.push("");
    }
  }

  // Passed guards summary
  const passedGuards = report.results.filter((r) => r.passed);
  if (passedGuards.length > 0) {
    lines.push("### Passed Checks");
    lines.push("");
    for (const guard of passedGuards) {
      lines.push(`- **${formatGuardName(guard.guard)}**: ${guard.details[0] ?? "OK"}`);
    }
    lines.push("");
  }

  // Footer
  lines.push("---");
  lines.push(
    "*Generated by [@silence/sentinel](https://github.com/SILENCE-OBJECTS) — automated compliance agent*"
  );

  return lines.join("\n");
}

/**
 * Generate a compact single-line summary for CLI output.
 */
export function generateCliSummary(report: ComplianceReport): string {
  const status = report.passed ? "PASSED" : "FAILED";
  const passCount = report.results.filter((r) => r.passed).length;
  return `SENTINEL ${status} | Score: ${report.score}/100 (${report.grade}) | Guards: ${passCount}/${report.results.length} passed`;
}

/**
 * Generate a detailed console report with colored output hints.
 */
export function generateConsoleReport(report: ComplianceReport): string {
  const lines: string[] = [];

  lines.push("");
  lines.push("=".repeat(60));
  lines.push("  SILENCE SENTINEL — Compliance Report");
  lines.push("=".repeat(60));
  lines.push("");
  lines.push(`  Score:  ${report.score}/100 (Grade: ${report.grade})`);
  lines.push(`  Status: ${report.passed ? "PASSED" : "FAILED"}`);
  lines.push("");
  lines.push("-".repeat(60));

  for (const result of report.results) {
    const icon = result.passed ? "[PASS]" : "[FAIL]";
    lines.push(
      `  ${icon} ${formatGuardName(result.guard).padEnd(25)} ${result.violations} violation(s)`
    );

    if (!result.passed) {
      for (const detail of result.details.slice(0, 5)) {
        lines.push(`         ${detail}`);
      }
      if (result.details.length > 5) {
        lines.push(
          `         ... and ${result.details.length - 5} more`
        );
      }
    }
  }

  lines.push("");
  lines.push("-".repeat(60));

  if (report.passed) {
    lines.push("  DEPLOY AUTHORIZED — all checks passed");
  } else {
    lines.push("  DEPLOY BLOCKED — fix violations before merge");
  }

  lines.push("=".repeat(60));
  lines.push("");

  return lines.join("\n");
}

/**
 * Format guard name for display.
 */
function formatGuardName(guard: string): string {
  return guard
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

/**
 * Get an appropriate indicator for the score.
 */
function getScoreEmoji(score: number): string {
  if (score >= 95) return "[A+]";
  if (score >= 80) return "[OK]";
  if (score >= 70) return "[--]";
  if (score >= 50) return "[!!]";
  return "[XX]";
}

/**
 * Format a single guard result for individual guard runs.
 */
export function formatGuardResult(result: GuardResult): string {
  const lines: string[] = [];
  const icon = result.passed ? "[PASS]" : "[FAIL]";

  lines.push("");
  lines.push(`${icon} ${formatGuardName(result.guard)} Guard`);
  lines.push("-".repeat(40));

  if (result.violations === 0) {
    lines.push("  No violations detected.");
  } else {
    lines.push(`  ${result.violations} violation(s) found:`);
    lines.push("");
    for (const detail of result.details) {
      lines.push(`  - ${detail}`);
    }
  }

  lines.push("");
  return lines.join("\n");
}
